### PR TITLE
BibFormat: cvlatex improvements

### LINKED ISSUE #213: Cv format commenting improvements
My beloved wife reports that it's currently technically difficult to remove comments from our LaTeX output formats. E.g.:

https://inspirehep.net/search?ln=it&ln=it&p=storaci&of=tlcv&action_search=Cerca&sf=earliestdate&so=d&rm=&rg=25&sc=0

E.g. one would need to use regular expression in order to automatically strip away % in front of lines such as:

`%2 citations counted in INSPIRE as of 24 Aug 2016`

or

`%(Aug 23, 2016)`

Not all editor supports it and not all users master regexp.

One possible quick solution is e.g. to add a constant improbable suffix after the percentage char, so that even dummy editors can search and replace them.

E.g. 
- `%-- 2 citations counted in INSPIRE as of 24 Aug 2016`
- `%== (Aug 23, 2016)`

### PR DESCRIPTION
**Pull request by michamos**
* inspire part of inspirehep/invenio#377

* closes #213

Signed-off-by: Micha Moskovic <michamos@gmail.com>

### CODE REVIEW

**Comment by tsgit** [comment]
@michamos  this doesn't work as advertised. please test

https://github.com/inspirehep/invenio/blob/prod/modules/websearch/lib/search_engine_cvifier.py#L79

  \newcommand{\href}[1]{}

this gobbles one argument, but here 

+\href{<BFE_SERVER_INFO var="absoluterecurl" />}{INSPIRE-HEP entry}

you have 2, so you end up with a meaningless "INSPIRE-HEP entry" when showlinks is false. see attched pdf

T.


[foo.pdf](https://github.com/inspirehep/inspire/files/720202/foo.pdf)

**Comment by tsgit** [comment]
needs https://github.com/inspirehep/invenio/pull/380

**Comment by tsgit** [comment]
see attached PDF. I think the spacing is odd, the citations should be on their own line, no?

also, should there be a separator between report-numbers and INSPIRE-HEP entry ?

[cvbadspacing.pdf](https://github.com/inspirehep/inspire/files/722149/cvbadspacing.pdf)

on output of `/search?p=find+a+ellis+and+refersto+a+witten&of=tlcv`

I get error about unescaped `&` :

```
[15] [16] [17] [18] [19] [20] [21] [22]
! Misplaced alignment tab character &.
l.2199 ...H. 7000 (93/11,rec.Nov.) 22 p. Texas A &
                                                   M Univ. College Station -...

? 
[23] [24]
! Misplaced alignment tab character &.
l.2342 ...476 (92/04,rec.Jun.) 18 p. and Texas A &
                                                   M Univ. College Station -...

? 
```

so looks like some more improvements are in order.

**Comment by tsgit** [comment]
I deployed 
https://github.com/inspirehep/invenio/pull/377
https://github.com/inspirehep/invenio/pull/379
https://github.com/inspirehep/invenio/pull/380

what remains to be done is fixes here to spacing and TeX special character escaping

**Comment by michamos** [comment]
@tsgit, I am sorry for all the extra work you had to do. Next time I will test it on inspire-test first.
I will look into the remaining bugs.

**Comment by michamos** [comment]
I took care of the spacing issue, also addressing the redefined `\href` macro which might indeed be confusing.
The escaping is completely unrelated to this issue and I don't understand (nor want to) bibformat well-enough to fix it.

**Comment by tsgit** [comment]
mmh, another minor complaint about spacing, which I only noticed after deploying:

looking at

http://inspirehep.net/search?p=find+a+ellis+and+refersto+a+witten&of=tlcv

there is no empty line between `\citations{}` and the following `%\cite{}` and \item{} section

```
%\cite{Ellis:2016ipm}
\item%{Ellis:2016ipm}
{\bf ``Starobinsky-Like Inflation and Neutrino Masses in a No-Scale SO(10) Model''}
  \\{}J.~Ellis, M.~A.~G.~Garcia, N.~Nagata, D.~V.~Nanopoulos and K.~A.~Olive.
  \\{}arXiv:1609.05849 [hep-ph]
  \\{}DOI:10.1088/1475-7516/2016/11/018
  \\{}JCAP {\bf 1611}, no. 11, 018 (2016)
  \\{}KCL-PH-TH-2016-54, CERN-TH-2016-188, UT-16-29, ACT-05-16, MI-TH-1625, UMN-TH-3603-16, FTPI-MINN-16-26
%(Sep 19, 2016)
\inspireurl{http://inspirehep.net/record/1487260}
\citations{1 citations counted in INSPIRE as of 24 Jan 2017}
%\cite{Boonekamp:2006ikz}
\item%{Boonekamp:2006ikz}
{\bf ``The Minimal Supersymmetric Standard Model with CP Phases''}
  \\{}M.~Boonekamp {\it et al.}.
  \\{}DOI:10.5170/CERN-2006-009.97
%(2006)
\inspireurl{http://inspirehep.net/record/1479591}

%\cite{Ellis:2016spb}
\item%{Ellis:2016spb}
{\bf ``Higgs Inflation, Reheating and Gravitino Production in No-Scale Supersymmetric GUTs''}
  \\{}J.~Ellis, H.~J.~He and Z.~Z.~Xianyu.
  \\{}arXiv:1606.02202 [hep-ph]
  \\{}DOI:10.1088/1475-7516/2016/08/068
  \\{}JCAP {\bf 1608}, no. 08, 068 (2016)
  \\{}KCL-PH-TH-2016-33, CERN-TH-2016-134
%(Jun 7, 2016)
\inspireurl{http://inspirehep.net/record/1468076}
\citations{4 citations counted in INSPIRE as of 24 Jan 2017}
%\cite{Ellis:2016atb}
\item%{Ellis:2016atb}
{\bf ``$W_\infty$ Algebras, Hawking Radiation and Information Retention by Stringy Black Holes''}
  \\{}J.~Ellis, N.~E.~Mavromatos and D.~V.~Nanopoulos.
  \\{}arXiv:1605.01653 [hep-th]
  \\{}DOI:10.1103/PhysRevD.94.025007
  \\{}Phys.\ Rev.\ D {\bf 94}, no. 2, 025007 (2016)
  \\{}CERN-TH-2016-105
%(May 5, 2016)
\inspireurl{http://inspirehep.net/record/1455874}
\citations{2 citations counted in INSPIRE as of 24 Jan 2017}
%\cite{Campbell:2016ivq}
\item%{Campbell:2016ivq}
```

**Pull request merged**
