### PR TITLE
bibcheck: new plugin - fix_cds_import_bug

### PR DESCRIPTION
**Pull request by ksachs**
* moves 502 $$abc to $$bcd

Signed-off-by: Kirsten Sachs <kirsten.sachs@desy.de>

### CODE REVIEW

**Comment by ksachs** [comment]
I know the code is ugly - but it works.
Hopefully obsolete soon.

**Comment by kaplun** [comment]
@ksachs I missed this one. I guess we want to merge and run it, right?

**Comment by ksachs** [comment]
up to you. I guess it makes live easier to convert to the new datamodel. And it causes less problems in 'missing' dates for texkeys.

**Comment by kaplun** [comment]
Is there a safe query to make it work only on CDS imported theses?

**Comment by ksachs** [comment]
See changed rules.cfg

[fix_cds_import_bug]
check = fix_cds_import_bug
filter_pattern = 502__c:/^[12]/
filter_collection = HEP

The plugin modifies the record only after several checks.

**Pull request closed without merging**
