### PR TITLE
New bibtasklet: bst_check4template

### PR DESCRIPTION
**Pull request by ksachs**
* fully tested

Signed-off-by: Kirsten Sachs <kirsten.sachs@desy.de>

### CODE REVIEW

**Comment by kaplun** [comment]
Merged and deployed. @ksachs do you take care of scheduling it? Additionally, we have to see if these new templates don't show up in regular BibEdit interface, thus interfering with cataloguers...

**Comment by ksachs** [comment]
I have no idea how to schedule it. it should run with default settings, I guess once a day. 
darn - they show in the list of available templates. I havn't thought about that.

**Comment by kaplun** [comment]
I scheduled it, but it run without doing any correction. And it was quite fast.

**Comment by ksachs** [comment]
Is running smoothly.

To avoid the spurious templates in BibEdit. A simple solution would be to rename e.g. volatile_check_ignore_HEP.xml  to  volatile_check_HEP.xml_ignore
(anything that doesn't end in .xml) and adopt the code accordingly. Is that OK?

When changing a template one has to remember that one might have to change the ignore file too. So I would like to have them in the same directory. 
In a ideal case the information would be in the template directly, but then I need to different VOLATILE tags. Which means I would have to change bibedit_engine.py, bibedit_utils.py and bibrecord.py.

**Comment by kaplun** [comment]
I think we can you go ahead with your proposal for the `_ignore` suffix. We no longer aim for perfection on INSPIRE production, so a quick fix is surely welcomed :-)

**Pull request merged**
