### PR TITLE
Bibcheck: Journal names

### PR DESCRIPTION
**Pull request by ksachs**
Sorry - I messed up the commit again. squash & rebase didn't work as intended.
Can you still use this? Otherwise I start from scratch.

Before you add it to the regular bibcheck task it would be better to run it once manually.
The first run takes very long since it checks every name-variant of every journal. 
Running on modified records only is no problem.

### CODE REVIEW

**Comment by ksachs** [comment]
Instead of adding it to the regular every-two-hours rules.cfg it would go to a new rules_weekly.cfg.
E.g. as 

    [KAOS_journal_names]
    check = journal_names
    filter_collection = Journals

We can still decide on a syntax for the names, but this way I could easily filter the tickets in RT.

**Comment by kaplun** [comment]
Would you like one ticket per error?

**Comment by ksachs** [comment]
No, the default: one ticket per rule

**Comment by kaplun** [comment]
OK I leave the default. Let's hope it behaves as intended :)

**Comment by ksachs** [comment]
As mentioned above I would prefer some sort of cataloger initial/name in the name of the rule.
Better stop the currently running process.
With a new name it will assume it's a new rule and run all over again.

**Comment by kaplun** [comment]
yep. Too late :) I missed saving the file with the KAOS prefix. Anyway it is coming now. This is what happens when one is sick at home :dancer:

**Pull request closed without merging**
