### PR TITLE
bibcheck: new plugin - split_multiple_subfields

### PR DESCRIPTION
**Pull request by ksachs**
Please review carefully - not the best code.
Syntax of filter_field in rules.cfg has to be checked!

Signed-off-by: Kirsten Sachs <kirsten.sachs@desy.de>

### CODE REVIEW

**Comment by kaplun** [comment]
To be double eye-balled and tested by @ksachs on inspirevm16 once she has the rights :+1:

**Comment by ksachs** [comment]
as requested I tried to rebase against master - but I have no idea what I really did.
I guess I screwed it. 

mvtexkey_z2a.py should NOT be part of this commit.

rules.cfg should contain
[split_subject_kw]
check = split_multiple_subfields
check.fields = ["6531_a", "65017a", "695__a"]

split_multiple_subfields.py is fine and tested

Can you make sense out of this or shall I start from scratch with a new branch?

**Comment by kaplun** [comment]
Ah. Nope, not against master, but against prod. I will try to make sense out if though :-)

**Comment by kaplun** [comment]
> ~~ Ah. Nope, not against master, but against prod. I will try to make sense out it, though :-) ~~

Sorry, forget what I said. It's correct against master (for the inspire overlay). Although it's true that your PR is quite messy :stuck_out_tongue:

**Comment by kaplun** [comment]
@ksachs it's quite difficult to understand what you wanted to do. On the other hand if I look at: https://github.com/inspirehep/inspire/pull/99/files?diff=unified I see that the actual changes are not so much. Are these all and only the things you wanted to change?

**Comment by ksachs** [comment]
almost - as mentioned above

mvtexkey_z2a.py should not be changed

otherwise - yes that's all:
1 new file: split_multiple_subfields.py
and 3 lines added to rules.cfg

Sorry for the mess.

**Comment by kaplun** [comment]
Done. Deployed. Running :smile:

**Comment by ksachs** [comment]
GREAT!

**Pull request closed without merging**
