### PR TITLE
general: update URL to search tips

### PR DESCRIPTION
**Pull request by jalavik**
Signed-off-by: Jan Aage Lavik <jan.age.lavik@cern.ch>

### CODE REVIEW

**Comment by tsgit** [comment]
https://github.com/jalavik/inspire/blob/7193616e412759519160fc778fd57d7cde1eb2f1/feedboxes/portalbox-009-HepNames-rt-100.html#L11-L14

unrelated, but need to urlescape '&'

**Comment by kaplun** [comment]
@jalavik I guess after integrating @tsgit comment we can merge it.

**Comment by jalavik** [comment]
Indeed. I will fix and push

**Comment by jalavik** [comment]
Updated. Added you two as reviewers. @kaplun Guess we can merge?

**Comment by kaplun** [comment]
:shipit: :smile:

**Pull request merged**
